version: "3"
services:
    web:
        image: nginx
        ports:
            - 3200:80
        restart: always
        volumes:
            - "./default.conf:/etc/nginx/conf.d/default.conf"
            - "./www:/var/www/html"
        depends_on:
            - php
    php:
        image: nanoninja/php-fpm
        container_name: php_server
        volumes:
            - "./www:/var/www/html"
        restart: always
    db:
        image: mysql
        ports:
            - 3306:3306
        container_name: mydb
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
        environment:
            - PMA_HOST=mydb
        restart: always
        depends_on:
            - db
